config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'smoothies#index'

  resources :smoothies, only: [:index, :show, :new, :create, :destroy] do
    resources :doses, only: [:new, :create]
  end

  resources :doses, only: [:destroy]

  resources :ingredients, only: [:index, :new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, presence: true
  validates_uniqueness_of :ingredient, scope: :smoothie

  belongs_to :smoothie
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :doses
  has_many :smoothies, through: :doses
end

app/models/smoothie.rb
class Smoothie < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_smoothie, only: [:new, :create]

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.smoothie = @smoothie
    if @dose.save
      redirect_to smoothie_path(@smoothie)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy

    redirect_to smoothies_path
  end

  private

  def set_smoothie
    @smoothie = Smoothie.find(params[:smoothie_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :smoothie_id, :ingredient_id)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      redirect_to ingredients_path
    else
      render :new
    end
  end

  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy

    redirect_to ingredients_path
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:name, :img_url)
  end
end

app/controllers/smoothies_controller.rb
class SmoothiesController < ApplicationController
  before_action :find_smoothie, only: [:show, :destroy]

  def index
    @smoothies = Smoothie.all
    @search = params["search"]
    if @search.present?
      @name = @search["query"]
      @smoothies = Smoothie.where("name ILIKE ?", "%#{@name}%")
    end
  end

  def show; end

  def new
    @smoothie = Smoothie.new
  end

  def create
    @smoothie = Smoothie.new(smoothie_params)
    if @smoothie.save
      redirect_to smoothie_path(@smoothie)
    else
      render :new
    end
  end

  def destroy
    @smoothie.destroy
  end

  private

  def find_smoothie
    @smoothie = Smoothie.find(params[:id])
  end

  def smoothie_params
    params.require(:smoothie).permit(:name, :img_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/smoothies_helper.rb
module SmoothiesHelper
end

app/views/doses/new.html.erb
<div class='container mt-5'>
  <%= simple_form_for [@smoothie, @dose] do |f| %>
    <%= f.association :ingredient, as: :select %>
    <%= f.input :description, placeholder: '1/2 cup' %>
    <%= f.submit "Add ingredient", class: "btn btn-rounded btn-info" %>
  <% end %>
  <br>
  <%= link_to "Don't see your ingredient? Add one here!", new_ingredient_path %>
</div>

app/views/ingredients/index.html.erb
<div class="container mt-5">
  <div class="row justify-content-end">
    <%= link_to 'Back', smoothies_path, class: "btn btn-light btn-rounded" %>
    <%= link_to 'Add new ingredient', new_ingredient_path, class: "btn btn-info btn-rounded" %>
  </div>
  <div class="row mt-3">
    <% if @ingredients.empty? %>
      <div class="row justify-content-center">
          <h5>There is no ingredients yet.</h5>
      </div>
      <div class="row justify-content-center">
          <%= link_to 'Add the first ingredient!', new_ingredient_path, class: "btn btn-info btn-rounded" %>
      </div>
      <% else %>
      <div class="cards">
        <% @ingredients.each do |ingredient| %>
            <div class="card-trip">
              <img src="<%= ingredient.img_url %>">
            <div class="card-trip-infos">
              <div>
                <h2><%= ingredient.name %></h2>
              </div>
              <%= link_to '🗑', ingredient_path(ingredient), method: :delete, data: { confirm: "Are you sure?" } %>
            </div>
            </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/ingredients/new.html.erb
<div class='container mt-5'>
  <%= simple_form_for @ingredient do |f| %>
    <%= f.input :name %>
    <%= f.input :img_url, label: "Image URL" %>
    <%= f.submit "Add ingredient", class: "btn btn-rounded btn-info" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MisterSmoothie</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "components/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/smoothies/index.html.erb
<div class="banner">
  <div class="container col-lg-6">
    <h1>Share and discover the best smoothies!</h1>
    <%= simple_form_for :search, url: root_path, method: :get do |f| %>
    <div class="search-form-control form-group mt-3">
      <%# <%= f.input :name, input_html: {value: ""}, class: "form-control string required" %>
      <input class="form-control string required" type="text" name="search[query]" id="search_query" />
      <button name="button" type="submit" class="btn btn-info btn-rounded">
        <i class="fas fa-search"></i> Search
      </button>
    </div>
    <% end %>
  </div>
</div>
<div class="container mt-5">
  <% if @smoothies.empty? %>
    <div class="row justify-content-center">
        <h5>There is no smoothies yet.</h5>
    </div>
    <div class="row justify-content-center">
        <%= link_to 'Add the first smoothie!', new_smoothie_path, class: "btn btn-info btn-rounded" %>
    </div>
    <% else %>
    <div class="cards">
      <% @smoothies.each do |smoothie| %>
        <%= link_to smoothie_path(smoothie) do %>
          <div class="card-trip">
          <% if smoothie.img_url.nil? %>
            <%= image_tag 'smoothie_default_img.svg', id: "default-img" %>
          <% else %>
            <img src="<%= smoothie.img_url %>">
          <% end %>
          <div class="card-trip-infos">
            <div>
              <h2><%= smoothie.name %></h2>
            </div>
          </div>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/smoothies/new.html.erb
<div class='container mt-5'>
  <%= simple_form_for @smoothie do |f| %>
    <%= f.input :name %>
    <%= f.input :img_url, label: "Image URL" %>
    <%= f.submit "Add My Smoothie!", class: "btn btn-rounded btn-info" %>
  <% end %>
</div>

app/views/smoothies/show.html.erb
<div class='container recipe-card mt-5'>
  <div class='row justify-content-end'>
      <%= link_to 'Add ingredient', new_smoothie_dose_path(@smoothie), class: "btn btn-info btn-rounded" %>
  </div>
  <div class='row justify-content-center mt-3'>
    <div class='col-6'>
      <% if @smoothie.img_url.nil? %>
        <%= image_tag 'smoothie_default_img.svg', class: "avatar-extra-large" %>
      <% else %>
        <img src="<%= @smoothie.img_url %>" class="avatar-extra-large">
      <% end %>
    </div>
    <div class='col-6'>
      <% if @smoothie.doses %>
        <ul>
          <% @smoothie.doses.each do |dose| %>
            <li>
            <%= dose.ingredient.name %> - <%= dose.description %>
            <span><%= link_to '🗑', dose_path(dose), method: :delete %></span>
            </li>
          <% end %>
        </ul>
      <% else %>
        <p>Just water? 😁</p>
      <% end %>
    </div>
  </div>
</div>